# Generated by Django 4.2.2 on 2023-07-11 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardtitle',
            name='content',
            field=models.TextField(max_length=2000),
        ),
        migrations.DeleteModel(
            name='CardContent',
        ),
    ]
